#!/usr/bin/env python3
"""
gen_can.py — CAN boilerplate generator for the FSE DCU 2612.

Reads the vehicle DBC (single source of truth for the bit layout) and the
application YAML (message whitelist + UI intent) and generates:

  src/generated/dcu_can_gen.[ch]    pack/unpack/encode/decode per message
                                    (via `cantools generate_c_source`)
  src/generated/can_data_gen.h      struct can_data_snapshot — fields from the
                                    app_names of all RX signals
  src/generated/can_rx_gen.[ch]     RX dispatch: frame ID → unpack → snapshot,
                                    plus frame ID table for filter setup
  src/generated/ui_subjects_gen.[ch] LVGL subjects (observer pattern): one
                                    lv_subject_t per RX signal + init/update;
                                    plus, for every numeric signal that
                                    declares a label, unit, range or limits,
                                    a struct ui_signal_desc that carries all
                                    of it (caption, unit, decimals, bar range,
                                    warning and critical limits).

Pipeline:
  1. Validate YAML against DBC (names, app_name uniqueness, limit monotonicity,
     limits inside the range, ui block)
  2. Filter DBC to the YAML whitelist → temporary filtered DBC
  3. Run cantools generate_c_source on the filtered DBC
  4. Emit snapshot struct + RX dispatch from the app_name mappings
  5. Emit LVGL subjects + presentation descriptors from the app_name / ui /
     limits / range mappings

Usage (from project root with west venv active):
  python3 tools/codegen/gen_can.py

SPDX-License-Identifier: Apache-2.0
Copyright (c) 2026 Mario Wegmann
"""

from __future__ import annotations

import argparse
import math
import hashlib
import subprocess
import sys
import tempfile
from pathlib import Path

import cantools
import yaml
from cantools.database.can.c_source import camel_to_snake_case
from cantools.database.can.database import Database

# Must match the --database-name argument of the cantools call.
DATABASE_NAME = "dcu_can_gen"

# Order defines the monotonicity requirement.
LIMIT_KEYS = ("critical_low", "warning_low", "warning_high", "critical_high")

# Maps YAML limit key → #define suffix (signal-name-first naming convention).
LIMIT_DEFINE_SUFFIX = {
    "warning_low":   "WARN_LOW",
    "warning_high":  "WARN_HIGH",
    "critical_low":  "CRIT_LOW",
    "critical_high": "CRIT_HIGH",
}

RANGE_KEYS = ("min", "max")

# Keys allowed inside a signal's `ui:` block.
UI_KEYS = ("label", "short_label", "unit", "precision")

# Decimals a readout may show. More than this is beyond what any signal resolves.
UI_PRECISION_MAX = 4

# Bit assigned to each optional field of struct ui_signal_desc (see the header
# emitted by emit_subjects_header — the two must stay in step).
UI_FLAG_RANGE = "UI_SIG_RANGE"
UI_LIMIT_FLAGS = {
    "critical_low":  "UI_SIG_CRIT_LOW",
    "warning_low":   "UI_SIG_WARN_LOW",
    "warning_high":  "UI_SIG_WARN_HIGH",
    "critical_high": "UI_SIG_CRIT_HIGH",
}
UI_LIMIT_FIELDS = {
    "critical_low":  "crit_low",
    "warning_low":   "warn_low",
    "warning_high":  "warn_high",
    "critical_high": "crit_high",
}

# Keys allowed inside a signal's `persist:` block and the top-level `settings:`.
PERSIST_KEYS = ("default", "min", "max")

# Settings are stored as uint8_t in the NVS blob.
SETTING_VALUE_MAX = 255

VALID_DIRECTIONS = {"rx", "tx"}

PROJECT_ROOT = Path(__file__).resolve().parents[2]

GENERATED_BANNER = """\
/*
 * AUTO-GENERATED FILE — DO NOT EDIT.
 *
 * Generated by tools/codegen/gen_can.py
 * from dbc/dcu_can.dbc + dbc/dcu_app.yaml.
 *
 * Regenerate: python3 tools/codegen/gen_can.py
 */
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--dbc", type=Path, default=PROJECT_ROOT / "dbc" / "dcu_can.dbc",
        help="Path to the vehicle DBC (default: dbc/dcu_can.dbc)",
    )
    parser.add_argument(
        "--yaml", dest="yaml_path", type=Path,
        default=PROJECT_ROOT / "dbc" / "dcu_app.yaml",
        help="Path to the application YAML (default: dbc/dcu_app.yaml)",
    )
    parser.add_argument(
        "--out", type=Path, default=PROJECT_ROOT / "src" / "generated",
        help="Output directory (default: src/generated)",
    )
    return parser.parse_args()


def fail(errors: list[str]) -> None:
    for err in errors:
        print(f"error: {err}", file=sys.stderr)
    sys.exit(1)


# ── Validation ────────────────────────────────────────────────────────────────


def validate(db: Database, cfg: dict) -> list[str]:
    """Validate the YAML config against the DBC. Returns a list of errors."""
    errors: list[str] = []

    messages = cfg.get("messages")
    if not isinstance(messages, dict) or not messages:
        return ["YAML: 'messages' is missing or empty"]

    dbc_messages = {m.name: m for m in db.messages}
    seen_app_names: dict[str, str] = {}
    seen_setting_names: dict[str, str] = {}

    for msg_name, msg_cfg in messages.items():
        msg_cfg = msg_cfg or {}

        dbc_msg = dbc_messages.get(msg_name)
        if dbc_msg is None:
            errors.append(f"{msg_name}: message does not exist in the DBC")
            continue

        direction = msg_cfg.get("direction")
        if direction not in VALID_DIRECTIONS:
            errors.append(
                f"{msg_name}: direction must be 'rx' or 'tx' (got: {direction!r})"
            )

        if direction == "tx":
            period_ms = msg_cfg.get("period_ms")
            if period_ms is None:
                errors.append(f"{msg_name}: TX message requires 'period_ms'")
            elif not isinstance(period_ms, int) or period_ms <= 0:
                errors.append(
                    f"{msg_name}: period_ms must be a positive integer (got: {period_ms!r})"
                )

        dbc_signals = {s.name: s for s in dbc_msg.signals}

        for sig_name, sig_cfg in (msg_cfg.get("signals") or {}).items():
            sig_cfg = sig_cfg or {}
            origin = f"{msg_name}.{sig_name}"

            if sig_name not in dbc_signals:
                errors.append(f"{origin}: signal does not exist in the DBC message")
                continue

            app_name = sig_cfg.get("app_name")
            if app_name:
                if not app_name.isidentifier():
                    errors.append(f"{origin}: app_name '{app_name}' is not a valid C identifier")
                if app_name in seen_app_names:
                    errors.append(
                        f"{origin}: app_name '{app_name}' already used by "
                        f"{seen_app_names[app_name]}"
                    )
                seen_app_names[app_name] = origin

            limits = sig_cfg.get("limits")
            if limits:
                if not app_name:
                    errors.append(f"{origin}: limits requires an app_name")

                unknown = set(limits) - set(LIMIT_KEYS)
                if unknown:
                    errors.append(
                        f"{origin}: unknown limits keys {sorted(unknown)} "
                        f"(allowed: {list(LIMIT_KEYS)})"
                    )
                    continue

                non_numeric = [k for k in limits if not isinstance(limits[k], (int, float))]
                if non_numeric:
                    errors.append(f"{origin}: limits {non_numeric} are not numeric")
                    continue

                present_values = [limits[k] for k in LIMIT_KEYS if k in limits]
                if present_values != sorted(present_values):
                    errors.append(
                        f"{origin}: limits are not monotonic — expected "
                        f"critical_low <= warning_low <= warning_high <= critical_high"
                    )

            range_ = sig_cfg.get("range")
            if range_:
                if not app_name:
                    errors.append(f"{origin}: range requires an app_name")

                unknown = set(range_) - set(RANGE_KEYS)
                if unknown:
                    errors.append(
                        f"{origin}: unknown range keys {sorted(unknown)} "
                        f"(allowed: {list(RANGE_KEYS)})"
                    )
                    continue

                non_numeric = [k for k in range_ if not isinstance(range_[k], (int, float))]
                if non_numeric:
                    errors.append(f"{origin}: range {non_numeric} are not numeric")
                    continue

                if "min" in range_ and "max" in range_ and range_["min"] >= range_["max"]:
                    errors.append(
                        f"{origin}: range min ({range_['min']}) must be less than max ({range_['max']})"
                    )

            errors.extend(
                validate_ui(sig_cfg, origin, dbc_signals[sig_name], app_name)
            )

            persist = sig_cfg.get("persist")
            if persist is not None:
                errors.extend(
                    validate_persist(persist, origin, dbc_signals[sig_name],
                                     direction, app_name, seen_setting_names)
                )

    errors.extend(validate_settings_section(cfg, seen_setting_names))

    return errors


def validate_ui(sig_cfg: dict, origin: str, sig, app_name: str | None) -> list[str]:
    """
    Validate a signal's presentation data: the `ui:` block, and how its `limits`
    and `range` relate to each other.

    A limit outside the range is the error this exists to catch. The bar then
    ends before the limit does, so the readout can turn gold or red at a value
    the bar cannot show — or never turn at all on the bar.
    """
    errors: list[str] = []

    ui = sig_cfg.get("ui")
    if ui is not None:
        if not isinstance(ui, dict):
            errors.append(f"{origin}: ui must be a mapping")
        else:
            if not app_name:
                errors.append(f"{origin}: ui requires an app_name")

            unknown = set(ui) - set(UI_KEYS)
            if unknown:
                errors.append(
                    f"{origin}: unknown ui keys {sorted(unknown)} (allowed: {list(UI_KEYS)})"
                )

            for key in ("label", "short_label", "unit"):
                if key in ui and not isinstance(ui[key], str):
                    errors.append(f"{origin}: ui.{key} must be a string (got: {ui[key]!r})")

            if "precision" in ui:
                prec = ui["precision"]
                if isinstance(prec, bool) or not isinstance(prec, int) \
                        or not 0 <= prec <= UI_PRECISION_MAX:
                    errors.append(
                        f"{origin}: ui.precision must be an integer 0..{UI_PRECISION_MAX} "
                        f"(got: {prec!r})"
                    )
                elif prec > 0 and snapshot_c_type(sig) != "float":
                    errors.append(
                        f"{origin}: ui.precision {prec} on an integer signal — only a signal "
                        f"with a factor or offset in the DBC carries decimals"
                    )

    # A DBC unit that is not plain ASCII is what a wrongly decoded '°C' looks
    # like; it would end up on the display as it is. Only matters when the unit
    # is actually going to be used. (A malformed ui block was reported above.)
    ui_map = ui if isinstance(ui, dict) else {}
    presented = bool(sig_cfg.get("limits") or sig_cfg.get("range") or ui_map.get("label"))
    if presented and "unit" not in ui_map and sig.unit and not sig.unit.isascii():
        errors.append(
            f"{origin}: the DBC unit {sig.unit!r} is not plain ASCII — "
            f"set ui.unit explicitly"
        )

    limits = sig_cfg.get("limits")
    range_ = sig_cfg.get("range")
    if isinstance(limits, dict) and isinstance(range_, dict) \
            and all(isinstance(v, (int, float)) for v in list(limits.values()) + list(range_.values())):
        lo = range_.get("min")
        hi = range_.get("max")
        for key in LIMIT_KEYS:
            if key not in limits:
                continue
            value = limits[key]
            if (lo is not None and value < lo) or (hi is not None and value > hi):
                bound = f"[{lo if lo is not None else '-inf'}, {hi if hi is not None else '+inf'}]"
                errors.append(
                    f"{origin}: limit {key} ({value}) lies outside range {bound}"
                )

    return errors


def validate_persist(persist, origin, sig, direction, app_name,
                     seen_setting_names: dict[str, str]) -> list[str]:
    """Validate a signal-level `persist:` block. Returns a list of errors."""
    errors: list[str] = []

    if not isinstance(persist, dict):
        return [f"{origin}: persist must be a mapping (got: {persist!r})"]

    if direction != "tx":
        errors.append(f"{origin}: persist is only valid on TX signals")
    if not app_name:
        errors.append(f"{origin}: persist requires an app_name")

    unknown = set(persist) - set(PERSIST_KEYS)
    if unknown:
        errors.append(
            f"{origin}: unknown persist keys {sorted(unknown)} "
            f"(allowed: {list(PERSIST_KEYS)})"
        )
        return errors

    if "default" not in persist:
        errors.append(f"{origin}: persist requires 'default'")
        return errors

    non_int = [k for k in persist if not isinstance(persist[k], int)
               or isinstance(persist[k], bool)]
    if non_int:
        errors.append(f"{origin}: persist {sorted(non_int)} must be integers")
        return errors

    # Settings are packed as raw CAN values into a uint8_t blob field, so a
    # scaled or signed signal cannot round-trip losslessly.
    if sig.is_signed:
        errors.append(f"{origin}: persist requires an unsigned signal")
    if sig.scale != 1 or sig.offset != 0:
        errors.append(
            f"{origin}: persist requires scale 1 and offset 0 "
            f"(got scale={sig.scale}, offset={sig.offset})"
        )

    lo, hi = signal_int_range(sig)
    lo = persist.get("min", lo)
    hi = persist.get("max", hi)

    if lo > hi:
        errors.append(f"{origin}: persist min ({lo}) must not exceed max ({hi})")
    elif not lo <= persist["default"] <= hi:
        errors.append(
            f"{origin}: persist default ({persist['default']}) outside range [{lo}, {hi}]"
        )

    if hi > SETTING_VALUE_MAX:
        errors.append(
            f"{origin}: persist max ({hi}) exceeds {SETTING_VALUE_MAX} — "
            f"settings are stored as uint8_t"
        )

    if app_name:
        if app_name in seen_setting_names:
            errors.append(
                f"{origin}: setting name '{app_name}' already used by "
                f"{seen_setting_names[app_name]}"
            )
        seen_setting_names[app_name] = origin

    return errors


def validate_settings_section(cfg: dict,
                              seen_setting_names: dict[str, str]) -> list[str]:
    """Validate the top-level `settings:` block (settings without a CAN signal)."""
    errors: list[str] = []
    section = cfg.get("settings")

    if section is None:
        return errors
    if not isinstance(section, dict):
        return [f"settings: must be a mapping (got: {section!r})"]

    for name, s_cfg in section.items():
        s_cfg = s_cfg or {}
        origin = f"settings.{name}"

        if not isinstance(name, str) or not name.isidentifier():
            errors.append(f"{origin}: '{name}' is not a valid C identifier")
        if name in seen_setting_names:
            errors.append(
                f"{origin}: setting name '{name}' already used by "
                f"{seen_setting_names[name]}"
            )
        seen_setting_names[name] = origin

        unknown = set(s_cfg) - set(PERSIST_KEYS)
        if unknown:
            errors.append(
                f"{origin}: unknown keys {sorted(unknown)} (allowed: {list(PERSIST_KEYS)})"
            )
            continue

        if "default" not in s_cfg:
            errors.append(f"{origin}: requires 'default'")
            continue

        non_int = [k for k in s_cfg if not isinstance(s_cfg[k], int)
                   or isinstance(s_cfg[k], bool)]
        if non_int:
            errors.append(f"{origin}: {sorted(non_int)} must be integers")
            continue

        lo = s_cfg.get("min", 0)
        hi = s_cfg.get("max", SETTING_VALUE_MAX)

        if lo > hi:
            errors.append(f"{origin}: min ({lo}) must not exceed max ({hi})")
        elif not lo <= s_cfg["default"] <= hi:
            errors.append(
                f"{origin}: default ({s_cfg['default']}) outside range [{lo}, {hi}]"
            )

        if lo < 0 or hi > SETTING_VALUE_MAX:
            errors.append(
                f"{origin}: range [{lo}, {hi}] outside [0, {SETTING_VALUE_MAX}] — "
                f"settings are stored as uint8_t"
            )

    return errors


# ── DBC Filtering + cantools ──────────────────────────────────────────────────


def write_filtered_dbc(db: Database, selected: set[str], out_path: Path) -> None:
    """Dump a DBC containing only the messages selected in the YAML."""
    filtered = Database(
        messages=[m for m in db.messages if m.name in selected],
        nodes=db.nodes,
        buses=db.buses,
        version=db.version,
    )
    cantools.database.dump_file(filtered, str(out_path))


def run_cantools_codegen(dbc_path: Path, out_dir: Path) -> None:
    """Run `cantools generate_c_source` → dcu_can_gen.[ch] in out_dir."""
    cmd = [
        sys.executable, "-m", "cantools", "generate_c_source",
        "--database-name", "dcu_can_gen",
        "--use-float",
        "-o", str(out_dir),
        str(dbc_path),
    ]
    subprocess.run(cmd, check=True)


# ── Snapshot Struct + RX Dispatch Generation ─────────────────────────────────


def snapshot_c_type(sig) -> str:
    """Map a cantools signal to the C type used in the snapshot struct."""
    if sig.length == 1:
        return "bool"
    if sig.is_float or sig.scale != 1 or sig.offset != 0:
        return "float"
    base = "int" if sig.is_signed else "uint"
    for width in (8, 16, 32, 64):
        if sig.length <= width:
            return f"{base}{width}_t"
    raise ValueError(f"Signal {sig.name}: length {sig.length} not supported")


def signal_int_range(sig) -> tuple[int, int]:
    """
    Derive the valid raw integer range of a CAN signal.

    An explicit, non-degenerate DBC minimum/maximum wins.  Otherwise the range
    follows from the bit width — an unsigned N-bit signal covers [0, 2^N - 1].
    Most settings signals carry [0|0] in the DBC, which cantools reports as
    absent, so the bit width is what actually applies.
    """
    lo, hi = sig.minimum, sig.maximum
    if lo is not None and hi is not None and hi > lo:
        return int(lo), int(hi)
    if sig.is_signed:
        return -(1 << (sig.length - 1)), (1 << (sig.length - 1)) - 1
    return 0, (1 << sig.length) - 1


def collect_rx_messages(db: Database, cfg: dict) -> list[dict]:
    """
    Collect all direction==rx messages with their app_name-mapped signals.

    Returns a list of dicts:
      { "msg": cantools message, "snake": c_name,
        "signals": [(dbc_signal, app_name, c_type, limits, range_), ...],
        "ui": {app_name: <the signal's `ui:` block>, ...} }
    Only signals with an app_name are included (selection at signal level).
    """
    dbc_messages = {m.name: m for m in db.messages}
    result = []

    for msg_name, msg_cfg in cfg["messages"].items():
        msg_cfg = msg_cfg or {}
        if msg_cfg.get("direction") != "rx":
            continue

        dbc_msg = dbc_messages[msg_name]
        dbc_signals = {s.name: s for s in dbc_msg.signals}
        mapped = []
        ui_blocks: dict[str, dict] = {}
        for sig_name, sig_cfg in (msg_cfg.get("signals") or {}).items():
            sig_cfg = sig_cfg or {}
            app_name = sig_cfg.get("app_name")
            if app_name:
                sig = dbc_signals[sig_name]
                mapped.append((sig, app_name, snapshot_c_type(sig),
                               sig_cfg.get("limits"), sig_cfg.get("range")))
                ui_blocks[app_name] = sig_cfg.get("ui") or {}

        if mapped:
            result.append({
                "msg": dbc_msg,
                "snake": camel_to_snake_case(msg_name),
                "signals": mapped,
                "ui": ui_blocks,
            })

    return result


def collect_tx_signals(db: Database, cfg: dict) -> list[tuple]:
    """
    Collect all TX signals that carry an app_name for UI subject generation.

    Returns a list of (dbc_signal, app_name, c_type) tuples in YAML order.
    """
    dbc_messages = {m.name: m for m in db.messages}
    result = []

    for msg_name, msg_cfg in cfg["messages"].items():
        msg_cfg = msg_cfg or {}
        if msg_cfg.get("direction") != "tx":
            continue

        dbc_msg = dbc_messages[msg_name]
        dbc_signals = {s.name: s for s in dbc_msg.signals}

        for sig_name, sig_cfg in (msg_cfg.get("signals") or {}).items():
            sig_cfg = sig_cfg or {}
            app_name = sig_cfg.get("app_name")
            if app_name:
                sig = dbc_signals[sig_name]
                result.append((sig, app_name, snapshot_c_type(sig)))

    return result


def emit_tx_subjects_header(tx_signals: list[tuple]) -> str:
    lines = [GENERATED_BANNER]
    lines.append("#ifndef GENERATED_UI_TX_SUBJECTS_GEN_H\n#define GENERATED_UI_TX_SUBJECTS_GEN_H\n")
    lines.append("#include <lvgl.h>\n")
    lines.append("""\
/*
 * One value subject ui_tx_subj_<x> per TX signal with an app_name in dcu_app.yaml.
 *
 * These are a UI-side mirror only.  The UI writes them when the user operates a
 * control and widgets observe them for rendering.
 *
 * Threading: subjects belong to the LVGL thread.  The CAN TX thread must NOT
 * read them — it takes persistent values from the Settings service and volatile
 * ones from app_state, both of which are mutex-protected.  See the ownership
 * model in services/settings/settings.h.
 *
 * ui_tx_subjects_gen_init() must be called from the LVGL thread before any
 * screen that binds to these subjects is created.
 */
""")
    for sig, app_name, c_type in tx_signals:
        lines.append(f"extern lv_subject_t ui_tx_subj_{app_name};{'':<4}"
                     f"/**< {sig.name} ({subject_kind(c_type)}) */")
    lines.append("")
    lines.append("""\
/**
 * @brief Initializes all TX subjects to 0.
 * Call before screen creation so screens can bind widgets during construction.
 */
void ui_tx_subjects_gen_init(void);""")
    lines.append("\n#endif /* GENERATED_UI_TX_SUBJECTS_GEN_H */")
    return "\n".join(lines) + "\n"


def emit_tx_subjects_source(tx_signals: list[tuple]) -> str:
    lines = [GENERATED_BANNER]
    lines.append('#include "ui_tx_subjects_gen.h"\n')

    for _sig, app_name, _c_type in tx_signals:
        lines.append(f"lv_subject_t ui_tx_subj_{app_name};")

    lines.append("\nvoid ui_tx_subjects_gen_init(void)\n{")
    for _sig, app_name, c_type in tx_signals:
        if subject_kind(c_type) == "float":
            lines.append(f"    lv_subject_init_float(&ui_tx_subj_{app_name}, 0.0f);")
        else:
            lines.append(f"    lv_subject_init_int(&ui_tx_subj_{app_name}, 0);")
    lines.append("}")

    return "\n".join(lines) + "\n"


# ── Persistent Settings Schema Generation ─────────────────────────────────────


def collect_settings(db: Database, cfg: dict) -> list[dict]:
    """
    Collect every persistent setting, CAN-backed ones first, then standalone.

    CAN-backed settings are TX signals carrying a `persist:` block; standalone
    settings come from the top-level `settings:` section.  Both end up in the
    same enum setting_id, so the order here defines the on-flash layout — which
    is exactly why the schema hash exists (see settings_schema_hash).

    Returns a list of dicts:
      { "name": str, "default": int, "min": int, "max": int, "can_tx": bool }
    """
    dbc_messages = {m.name: m for m in db.messages}
    result: list[dict] = []

    for msg_name, msg_cfg in cfg["messages"].items():
        msg_cfg = msg_cfg or {}
        if msg_cfg.get("direction") != "tx":
            continue

        dbc_signals = {s.name: s for s in dbc_messages[msg_name].signals}

        for sig_name, sig_cfg in (msg_cfg.get("signals") or {}).items():
            sig_cfg = sig_cfg or {}
            persist = sig_cfg.get("persist")
            if not persist:
                continue

            lo, hi = signal_int_range(dbc_signals[sig_name])
            result.append({
                "name":    sig_cfg["app_name"],
                "default": persist["default"],
                "min":     persist.get("min", lo),
                "max":     persist.get("max", hi),
                "can_tx":  True,
            })

    for name, s_cfg in (cfg.get("settings") or {}).items():
        s_cfg = s_cfg or {}
        result.append({
            "name":    name,
            "default": s_cfg["default"],
            "min":     s_cfg.get("min", 0),
            "max":     s_cfg.get("max", SETTING_VALUE_MAX),
            "can_tx":  False,
        })

    return result


def settings_schema_hash(settings: list[dict]) -> int:
    """
    Hash the canonical schema description into a 32-bit value.

    Stored alongside the values in flash.  A mismatch on load means the schema
    changed since the blob was written, so the blob is discarded and defaults
    apply.  This is what makes inserting a setting in the middle safe: without
    it, every setting after the insertion point would silently inherit its
    neighbour's value.
    """
    canonical = ";".join(
        f"{s['name']}:{s['default']}:{s['min']}:{s['max']}:{int(s['can_tx'])}"
        for s in settings
    )
    return int.from_bytes(hashlib.sha256(canonical.encode("utf-8")).digest()[:4], "big")


def emit_settings_schema_header(settings: list[dict], schema_hash: int) -> str:
    lines = [GENERATED_BANNER]
    lines.append("#ifndef GENERATED_SETTINGS_SCHEMA_GEN_H\n"
                 "#define GENERATED_SETTINGS_SCHEMA_GEN_H\n")
    lines.append("#include <stdbool.h>\n#include <stdint.h>\n")
    lines.append("""\
/*
 * Schema for values persisted across reboots (see services/settings/settings.h).
 *
 * Sources, in this order:
 *   1. TX signals with a `persist:` block in dcu_app.yaml (can_tx = true)
 *   2. The top-level `settings:` section         (can_tx = false)
 *
 * The enum order defines the on-flash layout.  Any change to it also changes
 * SETTINGS_SCHEMA_HASH, which invalidates stored blobs automatically.
 */
""")

    lines.append("enum setting_id {")
    for i, s in enumerate(settings):
        assign = " = 0" if i == 0 else ""
        lines.append(f"    SETTING_{s['name'].upper()}{assign},")
    lines.append("    SETTING_COUNT,")
    lines.append("};\n")

    lines.append("""\
/** @brief Per-setting bounds and defaults. Indexed by enum setting_id. */
typedef struct {
    const char *name;   /**< Identifier from dcu_app.yaml; diagnostics only. */
    uint8_t     def;    /**< Applied when nothing valid is stored.           */
    uint8_t     min;    /**< Inclusive lower bound.                          */
    uint8_t     max;    /**< Inclusive upper bound.                          */
    bool        can_tx; /**< true → also transmitted in a TX frame.          */
} setting_desc_t;

extern const setting_desc_t settings_schema[SETTING_COUNT];
""")

    lines.append("/** @brief Hash over names, order, bounds and defaults of the schema above. */")
    lines.append(f"#define SETTINGS_SCHEMA_HASH 0x{schema_hash:08X}UL")
    lines.append("\n#endif /* GENERATED_SETTINGS_SCHEMA_GEN_H */")
    return "\n".join(lines) + "\n"


def emit_settings_schema_source(settings: list[dict]) -> str:
    lines = [GENERATED_BANNER]
    lines.append('#include "settings_schema_gen.h"\n')
    lines.append("const setting_desc_t settings_schema[SETTING_COUNT] = {")
    for s in settings:
        lines.append(
            f"    [SETTING_{s['name'].upper()}] = {{ "
            f'.name = "{s["name"]}", '
            f".def = {s['default']}, "
            f".min = {s['min']}, "
            f".max = {s['max']}, "
            f".can_tx = {str(s['can_tx']).lower()} }},"
        )
    lines.append("};")
    return "\n".join(lines) + "\n"


def collect_tx_messages(db: Database, cfg: dict) -> list[dict]:
    """
    Collect all direction==tx messages with their period_ms and settings.

    "settings" lists the signals of the message that carry a `persist:` block,
    as (struct field, enum setting_id) pairs — the mapping emit_tx_header()
    turns into the apply-settings helper, so can.c never spells it out.

    Returns a list of dicts:
      { "msg": cantools message, "snake": c_name, "period_ms": int,
        "settings": list[tuple[str, str]] }
    """
    dbc_messages = {m.name: m for m in db.messages}
    result = []

    for msg_name, msg_cfg in cfg["messages"].items():
        msg_cfg = msg_cfg or {}
        if msg_cfg.get("direction") != "tx":
            continue

        settings = []
        for sig_name, sig_cfg in (msg_cfg.get("signals") or {}).items():
            sig_cfg = sig_cfg or {}
            if sig_cfg.get("persist"):
                settings.append((camel_to_snake_case(sig_name),
                                 f"SETTING_{sig_cfg['app_name'].upper()}"))

        result.append({
            "msg":       dbc_messages[msg_name],
            "snake":     camel_to_snake_case(msg_name),
            "period_ms": msg_cfg["period_ms"],
            "settings":  settings,
        })

    return result


def emit_tx_header(tx_messages: list[dict]) -> str:
    """
    Emit can_tx_gen.h: per TX message a PERIOD_MS #define and, if it carries
    persisted signals, an apply-settings helper, plus the period LCM the
    scheduling tick wraps at.

    Usage in can.c (CAN_TX_PERIOD_MS is the thread base tick):
      if (s_tx_tick % (CAN_TX_GEN_<MSG>_PERIOD_MS / CAN_TX_PERIOD_MS) == 0) { ... }
      s_tx_tick++;
    Both values are compile-time constants, so the division folds away.

    The helper writes every `persist:` signal of the message from the Settings
    service's value array. Generating it is what keeps a newly persisted signal
    from being transmitted as a silent zero: adding it to the YAML is enough,
    no edit in can.c required.
    """
    lines = [GENERATED_BANNER]
    lines.append("#ifndef GENERATED_CAN_TX_GEN_H\n#define GENERATED_CAN_TX_GEN_H\n")
    lines.append(f'#include "{DATABASE_NAME}.h"')
    lines.append('#include "settings_schema_gen.h"\n')
    lines.append("""\
/*
 * TX message period constants (physical milliseconds from dcu_app.yaml).
 *
 * Intended use in can.c — CAN_TX_PERIOD_MS is the thread base-tick interval:
 *
 *   static uint32_t s_tx_tick = 0U;
 *   ...
 *   if (s_tx_tick % (CAN_TX_GEN_DCU_2_M_ABX_PERIOD_MS / CAN_TX_PERIOD_MS) == 0) {
 *       can_send_dcu2_mabx(...);
 *   }
 *   s_tx_tick++;
 *
 * Both operands are compile-time constants; the division folds to a literal.
 */
""")
    for entry in tx_messages:
        msg   = entry["msg"]
        snake = entry["snake"]
        ms    = entry["period_ms"]
        define_name = f"CAN_TX_GEN_{snake.upper()}_PERIOD_MS"
        lines.append(f"/** @brief {msg.name} (0x{msg.frame_id:03X}) TX period. */")
        lines.append(f"#define {define_name:<44} {ms}U\n")

    period_lcm = math.lcm(*(e["period_ms"] for e in tx_messages)) if tx_messages else 1
    lines.append(f"""\
/**
 * @brief Least common multiple of all TX periods, in milliseconds.
 *
 * The schedule above repeats itself every {period_lcm} ms, so a tick counter
 * wrapped at this value keeps every message's phase for good. Letting the
 * counter run to its own integer limit instead would shift the phase on
 * overflow, because the limit is not a multiple of the periods.
 */
#define CAN_TX_GEN_PERIOD_LCM_MS                     {period_lcm}U
""")

    for entry in tx_messages:
        if not entry["settings"]:
            continue
        msg   = entry["msg"]
        snake = entry["snake"]
        struct = f"struct {DATABASE_NAME}_{snake}_t"
        lines.append(f"""\
/**
 * @brief Copy every persisted {msg.name} signal into the frame struct.
 *
 * Generated from the `persist:` blocks in dcu_app.yaml. Signals without one
 * are left untouched — the caller owns those.
 *
 * @param msg       Frame struct to fill.
 * @param settings  Values from settings_get_all(), indexed by enum setting_id.
 */
static inline void can_tx_gen_{snake}_apply_settings(
    {struct} *msg, const uint8_t settings[SETTING_COUNT])
{{""")
        width = max(len(field) for field, _ in entry["settings"])
        for field, setting in entry["settings"]:
            lines.append(f"    msg->{field:<{width}} = settings[{setting}];")
        lines.append("}\n")

    lines.append("#endif /* GENERATED_CAN_TX_GEN_H */")
    return "\n".join(lines) + "\n"


def emit_data_header(rx_messages: list[dict]) -> str:
    lines = [GENERATED_BANNER]
    lines.append("#ifndef GENERATED_CAN_DATA_GEN_H\n#define GENERATED_CAN_DATA_GEN_H\n")
    lines.append("#include <stdint.h>")
    lines.append("#include <stdbool.h>\n")
    lines.append("""\
/**
 * @brief Snapshot of all decoded RX CAN signal values.
 *
 * Fields correspond to the app_names from dcu_app.yaml. Populated by
 * can_rx_gen_dispatch(); published to the app layer via can_data_chan
 * and stored there in app_state.
 */
struct can_data_snapshot {""")
    for entry in rx_messages:
        msg = entry["msg"]
        lines.append(f"\n    /* ── {msg.name} (0x{msg.frame_id:03X}) ── */\n")
        for sig, app_name, c_type, _limits, _range in entry["signals"]:
            lines.append(f"    {c_type:<8} {app_name};{'':<4}/**< {sig.name} */")
    lines.append("""
    /**
     * Zephyr uptime (ms) at the time of decoding.
     * Allows the app layer to detect stale data during CAN silence.
     */
    int64_t  timestamp_ms;
};""")
    lines.append("\n#endif /* GENERATED_CAN_DATA_GEN_H */")
    return "\n".join(lines) + "\n"


def emit_rx_dispatch_header(rx_messages: list[dict]) -> str:
    lines = [GENERATED_BANNER]
    lines.append("#ifndef GENERATED_CAN_RX_GEN_H\n#define GENERATED_CAN_RX_GEN_H\n")
    lines.append("#include <stdint.h>")
    lines.append("#include <stdbool.h>\n")
    lines.append('#include "can_data_gen.h"\n')
    lines.append(f"""\
/** @brief Number of RX frame IDs (size of can_rx_gen_frame_ids). */
#define CAN_RX_GEN_NUM_FRAMES {len(rx_messages)}U

/**
 * @brief All RX frame IDs from dcu_app.yaml (direction: rx).
 * For filter setup: one can_add_rx_filter_msgq() call per entry.
 */
extern const uint32_t can_rx_gen_frame_ids[CAN_RX_GEN_NUM_FRAMES];

/**
 * @brief Decodes an RX frame and writes the signal values into @p snap.
 *
 * Handles all direction:rx messages from dcu_app.yaml. Fields without
 * a matching frame ID remain unchanged (accumulator semantics).
 *
 * @param frame_id  CAN frame ID (11-bit standard ID).
 * @param data      Frame payload buffer.
 * @param dlc       Number of valid payload bytes.
 * @param snap      Target snapshot; only fields of the matched message change.
 * @return          true if the frame ID was known and successfully decoded.
 */
bool can_rx_gen_dispatch(uint32_t frame_id, const uint8_t *data, uint8_t dlc,
                         struct can_data_snapshot *snap);""")
    lines.append("\n#endif /* GENERATED_CAN_RX_GEN_H */")
    return "\n".join(lines) + "\n"


def emit_rx_dispatch_source(rx_messages: list[dict]) -> str:
    lines = [GENERATED_BANNER]
    lines.append('#include "can_rx_gen.h"')
    lines.append(f'#include "{DATABASE_NAME}.h"\n')

    for entry in rx_messages:
        msg, snake = entry["msg"], entry["snake"]
        fn = f"{DATABASE_NAME}_{snake}"
        lines.append(f"/* ── {msg.name} (0x{msg.frame_id:03X}) ── */\n")
        lines.append(f"static bool apply_{snake}(const uint8_t *data, uint8_t dlc,")
        lines.append(f"{'':<{len('static bool apply_' + snake) + 1}}struct can_data_snapshot *snap)")
        lines.append("{")
        lines.append(f"    struct {fn}_t msg;\n")
        lines.append(f"    if ({fn}_unpack(&msg, data, dlc) != 0) {{")
        lines.append("        return false;")
        lines.append("    }\n")
        for sig, app_name, c_type, _limits, _range in entry["signals"]:
            field = camel_to_snake_case(sig.name)
            if c_type == "bool":
                rhs = f"(msg.{field} != 0u)"
            elif c_type == "float":
                rhs = f"{fn}_{field}_decode(msg.{field})"
            else:
                rhs = f"msg.{field}"
            lines.append(f"    snap->{app_name:<24} = {rhs};")
        lines.append("\n    return true;")
        lines.append("}\n")

    ids = ",\n".join(
        f"    {DATABASE_NAME.upper()}_{e['snake'].upper()}_FRAME_ID"
        for e in rx_messages
    )
    lines.append(f"const uint32_t can_rx_gen_frame_ids[CAN_RX_GEN_NUM_FRAMES] = {{\n{ids},\n}};\n")

    lines.append("""\
bool can_rx_gen_dispatch(uint32_t frame_id, const uint8_t *data, uint8_t dlc,
                         struct can_data_snapshot *snap)
{
    switch (frame_id) {""")
    for entry in rx_messages:
        snake = entry["snake"]
        lines.append(f"    case {DATABASE_NAME.upper()}_{snake.upper()}_FRAME_ID:")
        lines.append(f"        return apply_{snake}(data, dlc, snap);")
    lines.append("""\
    default:
        return false;
    }
}""")
    return "\n".join(lines) + "\n"


# ── LVGL Subject Generation ───────────────────────────────────────────────────


def subject_kind(c_type: str) -> str:
    """Map a snapshot C type to the LVGL subject kind ('int' or 'float')."""
    return "float" if c_type == "float" else "int"


def c_float(value: float | int) -> str:
    return f"{float(value)}f"


def c_str(text: str) -> str:
    """A C string literal. Non-ASCII stays as UTF-8 — the sources are UTF-8."""
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def collect_ui_descriptors(rx_messages: list[dict]) -> list[dict]:
    """
    Build the presentation descriptor of every RX signal that declares one.

    A signal is presented when it is a number (not a flag) and says anything
    about how: a label, a unit, a range or limits. Everything else — the status
    LEDs, the shutdown-circuit contacts, raw state values — gets a subject only.

    The unit comes from `ui.unit`, else from the DBC; the YAML never has to
    repeat what the DBC already says. `short_label` falls back to `label`.
    """
    descs: list[dict] = []

    for entry in rx_messages:
        for sig, app_name, c_type, limits, range_ in entry["signals"]:
            if c_type == "bool":
                continue

            ui = entry["ui"].get(app_name) or {}
            label = ui.get("label") or ""
            short = ui.get("short_label") or label
            unit = ui["unit"] if "unit" in ui else (sig.unit or "")

            if not (label or short or unit or limits or range_):
                continue

            precision = ui.get("precision", 0)
            is_float = subject_kind(c_type) == "float"

            descs.append({
                "app_name":  app_name,
                "signal":    sig.name,
                "label":     label,
                "short":     short,
                "unit":      unit,
                "fmt":       f"%.{precision}f" if is_float else "%d",
                "precision": precision,
                "limits":    limits or {},
                "range":     range_ or {},
            })

    return descs


def emit_subjects_header(rx_messages: list[dict]) -> str:
    lines = [GENERATED_BANNER]
    lines.append("#ifndef GENERATED_UI_SUBJECTS_GEN_H\n#define GENERATED_UI_SUBJECTS_GEN_H\n")
    lines.append("#include <stdint.h>\n")
    lines.append("#include <lvgl.h>\n")
    lines.append('#include "can_data_gen.h"\n')
    lines.append("""\
/*
 * One value subject ui_subj_<x> per RX signal (app_name from dcu_app.yaml).
 *
 * Numeric signals that say how they are presented — a label, a unit, a range
 * or limits — also get a descriptor ui_sig_<x>, defined at the end of this
 * header. It carries everything a screen needs to show the value, so that no
 * screen has to repeat a caption, a unit, a number of decimals, a bar range or
 * a limit of its own. The YAML is the only place those live.
 *
 * The UI_<X>_WARN_* / _CRIT_* / _RANGE_* defines carry the same numbers as
 * plain constants. A screen uses the descriptor. The defines are for code that
 * has no business with LVGL subjects — the lighting module, which runs in its
 * own thread and must not touch them, reads its thresholds from here.
 *
 * Threading: ui_subjects_gen_init() and ui_subjects_gen_update() must ONLY
 * be called from the LVGL thread.
 */

/** @brief Which optional fields of a struct ui_signal_desc are meaningful. */
enum ui_signal_flag {
    UI_SIG_RANGE     = 1U << 0, /**< range_min / range_max are set. */
    UI_SIG_CRIT_LOW  = 1U << 1, /**< crit_low is set.               */
    UI_SIG_WARN_LOW  = 1U << 2, /**< warn_low is set.               */
    UI_SIG_WARN_HIGH = 1U << 3, /**< warn_high is set.              */
    UI_SIG_CRIT_HIGH = 1U << 4, /**< crit_high is set.              */
};

/**
 * @brief How one signal is presented, as declared in dcu_app.yaml.
 *
 * Values are physical (after the DBC factor and offset), the same units the
 * signal's subject carries.
 *
 * The limits follow the YAML semantics, all of them optional:
 *   value < crit_low   → critical      value > warn_high → warning
 *   value < warn_low   → warning       value > crit_high → critical
 * A limit whose flag is not set must not be read.
 */
struct ui_signal_desc {
    lv_subject_t *subject;      /**< The signal's value subject.                 */
    const char   *label;        /**< Full caption, e.g. "HV Accu Voltage".       */
    const char   *short_label;  /**< Compact caption; equals label if not given. */
    const char   *unit;         /**< Unit suffix, "" if none. UTF-8.             */
    const char   *fmt;          /**< printf format for the value: "%d" for an
                                     integer subject, "%.Nf" for a float one.    */
    uint8_t       precision;    /**< Decimals in fmt; 0 for an integer subject.  */
    uint8_t       flags;        /**< enum ui_signal_flag bits.                   */
    float         range_min;    /**< Display range, lower end.                   */
    float         range_max;    /**< Display range, upper end.                   */
    float         crit_low;     /**< Critical below this.                        */
    float         warn_low;     /**< Warning below this.                         */
    float         warn_high;    /**< Warning above this.                         */
    float         crit_high;    /**< Critical above this.                        */
};
""")
    for entry in rx_messages:
        msg = entry["msg"]
        lines.append(f"/* ── {msg.name} (0x{msg.frame_id:03X}) ── */\n")
        for sig, app_name, c_type, limits, range_ in entry["signals"]:
            lines.append(f"extern lv_subject_t ui_subj_{app_name};{'':<4}"
                         f"/**< {sig.name} ({subject_kind(c_type)}) */")
            prefix = f"UI_{app_name.upper()}"
            if limits:
                for key, suffix in LIMIT_DEFINE_SUFFIX.items():
                    if key in limits:
                        define_name = f"{prefix}_{suffix}"
                        lines.append(f"#define {define_name:<44} {c_float(limits[key])}")
            if range_:
                if "min" in range_:
                    lines.append(f"#define {prefix + '_RANGE_MIN':<44} {c_float(range_['min'])}")
                if "max" in range_:
                    lines.append(f"#define {prefix + '_RANGE_MAX':<44} {c_float(range_['max'])}")
        lines.append("")

    descs = collect_ui_descriptors(rx_messages)
    lines.append("/* ── Presentation descriptors ── */\n")
    for d in descs:
        lines.append(f"extern const struct ui_signal_desc ui_sig_{d['app_name']};")
    lines.append("")
    lines.append("""\
/**
 * @brief Initializes all subjects to 0.
 * Call before screen creation so screens can bind widgets during construction.
 */
void ui_subjects_gen_init(void);

/**
 * @brief Transfers a CAN snapshot into all subjects.
 *
 * lv_subject_set_*() only notifies observers on value change.
 *
 * @param snap  Snapshot from UI_CMD_UPDATE_DATA (app layer → UI).
 */
void ui_subjects_gen_update(const struct can_data_snapshot *snap);""")
    lines.append("\n#endif /* GENERATED_UI_SUBJECTS_GEN_H */")
    return "\n".join(lines) + "\n"


def emit_ui_descriptor_defs(descs: list[dict]) -> list[str]:
    """One `const struct ui_signal_desc` definition per descriptor."""
    lines: list[str] = []

    for d in descs:
        flags: list[str] = []
        fields: dict[str, str] = {}

        if d["range"]:
            flags.append(UI_FLAG_RANGE)
            fields["range_min"] = c_float(d["range"].get("min", 0))
            fields["range_max"] = c_float(d["range"].get("max", 0))
        for key in LIMIT_KEYS:
            if key in d["limits"]:
                flags.append(UI_LIMIT_FLAGS[key])
                fields[UI_LIMIT_FIELDS[key]] = c_float(d["limits"][key])

        lines.append(f"/* {d['signal']} */")
        lines.append(f"const struct ui_signal_desc ui_sig_{d['app_name']} = {{")
        lines.append(f"    .subject     = &ui_subj_{d['app_name']},")
        lines.append(f"    .label       = {c_str(d['label'])},")
        lines.append(f"    .short_label = {c_str(d['short'])},")
        lines.append(f"    .unit        = {c_str(d['unit'])},")
        lines.append(f"    .fmt         = {c_str(d['fmt'])},")
        lines.append(f"    .precision   = {d['precision']}U,")
        lines.append(f"    .flags       = {' | '.join(flags) if flags else '0U'},")
        for name, value in fields.items():
            lines.append(f"    .{name:<11} = {value},")
        lines.append("};\n")

    return lines


def emit_subjects_source(rx_messages: list[dict]) -> str:
    all_signals = [
        (sig, app_name, c_type, limits, range_)
        for entry in rx_messages
        for sig, app_name, c_type, limits, range_ in entry["signals"]
    ]

    lines = [GENERATED_BANNER]
    lines.append('#include "ui_subjects_gen.h"\n')

    for _sig, app_name, _c_type, _limits, _range in all_signals:
        lines.append(f"lv_subject_t ui_subj_{app_name};")

    lines.append("\nvoid ui_subjects_gen_init(void)\n{")
    for _sig, app_name, c_type, _limits, _range in all_signals:
        if subject_kind(c_type) == "float":
            lines.append(f"    lv_subject_init_float(&ui_subj_{app_name}, 0.0f);")
        else:
            lines.append(f"    lv_subject_init_int(&ui_subj_{app_name}, 0);")
    lines.append("}\n")

    lines.append("void ui_subjects_gen_update(const struct can_data_snapshot *snap)\n{")
    for _sig, app_name, c_type, _limits, _range in all_signals:
        if subject_kind(c_type) == "float":
            lines.append(f"    lv_subject_set_float(&ui_subj_{app_name}, snap->{app_name});")
        else:
            lines.append(f"    lv_subject_set_int(&ui_subj_{app_name}, (int32_t)snap->{app_name});")
    lines.append("}\n")

    for d in emit_ui_descriptor_defs(collect_ui_descriptors(rx_messages)):
        lines.append(d)

    return "\n".join(lines) + "\n"


# ── Main ──────────────────────────────────────────────────────────────────────


def main() -> None:
    args = parse_args()

    if not args.dbc.is_file():
        fail([f"DBC not found: {args.dbc}"])
    if not args.yaml_path.is_file():
        fail([f"YAML not found: {args.yaml_path}"])

    db = cantools.database.load_file(str(args.dbc))
    with open(args.yaml_path, encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    errors = validate(db, cfg)
    if errors:
        fail(errors)

    selected = set(cfg["messages"].keys())
    args.out.mkdir(parents=True, exist_ok=True)

    # Stage 1: filtered DBC → cantools C code
    with tempfile.TemporaryDirectory() as tmp:
        filtered_dbc = Path(tmp) / "dcu_can_filtered.dbc"
        write_filtered_dbc(db, selected, filtered_dbc)
        run_cantools_codegen(filtered_dbc, args.out)

    # Stage 2: snapshot struct + RX dispatch + TX periods
    rx_messages = collect_rx_messages(db, cfg)
    tx_messages = collect_tx_messages(db, cfg)
    tx_signals  = collect_tx_signals(db, cfg)
    (args.out / "can_data_gen.h").write_text(emit_data_header(rx_messages), encoding="utf-8")
    (args.out / "can_rx_gen.h").write_text(emit_rx_dispatch_header(rx_messages), encoding="utf-8")
    (args.out / "can_rx_gen.c").write_text(emit_rx_dispatch_source(rx_messages), encoding="utf-8")
    (args.out / "can_tx_gen.h").write_text(emit_tx_header(tx_messages), encoding="utf-8")

    # Stage 3: LVGL subjects — RX (CAN → UI) + TX (UI → CAN)
    (args.out / "ui_subjects_gen.h").write_text(
        emit_subjects_header(rx_messages), encoding="utf-8")
    (args.out / "ui_subjects_gen.c").write_text(
        emit_subjects_source(rx_messages), encoding="utf-8")
    (args.out / "ui_tx_subjects_gen.h").write_text(
        emit_tx_subjects_header(tx_signals), encoding="utf-8")
    (args.out / "ui_tx_subjects_gen.c").write_text(
        emit_tx_subjects_source(tx_signals), encoding="utf-8")

    # Stage 4: persistent settings schema
    settings = collect_settings(db, cfg)
    schema_hash = settings_schema_hash(settings)
    (args.out / "settings_schema_gen.h").write_text(
        emit_settings_schema_header(settings, schema_hash), encoding="utf-8")
    (args.out / "settings_schema_gen.c").write_text(
        emit_settings_schema_source(settings), encoding="utf-8")

    total_signals = sum(
        len((m or {}).get("signals") or {}) for m in cfg["messages"].values()
    )
    rx_signal_count = sum(len(e["signals"]) for e in rx_messages)
    limited_count = sum(
        1 for e in rx_messages
        for _sig, _app_name, _c_type, limits, _range in e["signals"]
        if limits
    )
    range_count = sum(
        1 for e in rx_messages
        for _sig, _app_name, _c_type, _limits, range_ in e["signals"]
        if range_
    )
    print(f"OK: {len(selected)} messages ({len(db.messages)} in DBC), "
          f"{total_signals} signals mapped, {limited_count} with level bindings, "
          f"{range_count} with range defines, {len(tx_messages)} TX period(s)")
    ui_desc_count = len(collect_ui_descriptors(rx_messages))
    print(f"    UI signals:  {ui_desc_count} with a presentation descriptor")
    print(f"    RX dispatch: {len(rx_messages)} messages, "
          f"{rx_signal_count} snapshot fields")
    print(f"    TX subjects: {len(tx_signals)} signals")
    can_backed = sum(1 for s in settings if s["can_tx"])
    print(f"    Settings:    {len(settings)} persistent "
          f"({can_backed} CAN-backed), schema hash 0x{schema_hash:08X}")
    for name in ("dcu_can_gen.c", "dcu_can_gen.h", "can_data_gen.h",
                 "can_rx_gen.c", "can_rx_gen.h", "can_tx_gen.h",
                 "ui_subjects_gen.c", "ui_subjects_gen.h",
                 "ui_tx_subjects_gen.c", "ui_tx_subjects_gen.h",
                 "settings_schema_gen.c", "settings_schema_gen.h"):
        print(f"  → {args.out / name}")


if __name__ == "__main__":
    main()