#!/usr/bin/env python3
"""
gen_can.py — CAN boilerplate generator for the FSE DCU 2612.

Reads the vehicle DBC (single source of truth for the bit layout) and the
application YAML (message whitelist + UI intent) and generates:

  src/generated/dcu_can_gen.[ch]    pack/unpack/encode/decode per message
                                    (via `cantools generate_c_source`)
  src/generated/can_data_gen.h      struct can_data_snapshot — fields from the
                                    app_names of all RX signals
  src/generated/can_rx_gen.[ch]     RX dispatch: frame ID → unpack → snapshot,
                                    plus frame ID table for filter setup
  src/generated/ui_subjects_gen.[ch] LVGL subjects (observer pattern): one
                                    lv_subject_t per RX signal + init/update;
                                    for signals with limits also a
                                    ui_bind_level_<x>(lv_obj_t*) helper that
                                    wires LV_STATE_USER_1/USER_2 state bindings
                                    directly against the value subject using
                                    lv_obj_bind_state_if_lt/gt.

Pipeline:
  1. Validate YAML against DBC (names, app_name uniqueness, limit monotonicity)
  2. Filter DBC to the YAML whitelist → temporary filtered DBC
  3. Run cantools generate_c_source on the filtered DBC
  4. Emit snapshot struct + RX dispatch from the app_name mappings
  5. Emit LVGL subjects + level-binding helpers from the app_name/limits mappings

Usage (from project root with west venv active):
  python3 tools/codegen/gen_can.py

SPDX-License-Identifier: Apache-2.0
Copyright (c) 2026 Mario Wegmann
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

import cantools
import yaml
from cantools.database.can.c_source import camel_to_snake_case
from cantools.database.can.database import Database

# Must match the --database-name argument of the cantools call.
DATABASE_NAME = "dcu_can_gen"

# Order defines the monotonicity requirement.
LIMIT_KEYS = ("critical_low", "warning_low", "warning_high", "critical_high")

VALID_DIRECTIONS = {"rx", "tx"}

PROJECT_ROOT = Path(__file__).resolve().parents[2]

GENERATED_BANNER = """\
/*
 * AUTO-GENERATED FILE — DO NOT EDIT.
 *
 * Generated by tools/codegen/gen_can.py
 * from dbc/dcu_can.dbc + dbc/dcu_app.yaml.
 *
 * Regenerate: python3 tools/codegen/gen_can.py
 */
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--dbc", type=Path, default=PROJECT_ROOT / "dbc" / "dcu_can.dbc",
        help="Path to the vehicle DBC (default: dbc/dcu_can.dbc)",
    )
    parser.add_argument(
        "--yaml", dest="yaml_path", type=Path,
        default=PROJECT_ROOT / "dbc" / "dcu_app.yaml",
        help="Path to the application YAML (default: dbc/dcu_app.yaml)",
    )
    parser.add_argument(
        "--out", type=Path, default=PROJECT_ROOT / "src" / "generated",
        help="Output directory (default: src/generated)",
    )
    return parser.parse_args()


def fail(errors: list[str]) -> None:
    for err in errors:
        print(f"error: {err}", file=sys.stderr)
    sys.exit(1)


# ── Validation ────────────────────────────────────────────────────────────────


def validate(db: Database, cfg: dict) -> list[str]:
    """Validate the YAML config against the DBC. Returns a list of errors."""
    errors: list[str] = []

    messages = cfg.get("messages")
    if not isinstance(messages, dict) or not messages:
        return ["YAML: 'messages' is missing or empty"]

    dbc_messages = {m.name: m for m in db.messages}
    seen_app_names: dict[str, str] = {}

    for msg_name, msg_cfg in messages.items():
        msg_cfg = msg_cfg or {}

        dbc_msg = dbc_messages.get(msg_name)
        if dbc_msg is None:
            errors.append(f"{msg_name}: message does not exist in the DBC")
            continue

        direction = msg_cfg.get("direction")
        if direction not in VALID_DIRECTIONS:
            errors.append(
                f"{msg_name}: direction must be 'rx' or 'tx' (got: {direction!r})"
            )

        dbc_signal_names = {s.name for s in dbc_msg.signals}

        for sig_name, sig_cfg in (msg_cfg.get("signals") or {}).items():
            sig_cfg = sig_cfg or {}
            origin = f"{msg_name}.{sig_name}"

            if sig_name not in dbc_signal_names:
                errors.append(f"{origin}: signal does not exist in the DBC message")
                continue

            app_name = sig_cfg.get("app_name")
            if app_name:
                if not app_name.isidentifier():
                    errors.append(f"{origin}: app_name '{app_name}' is not a valid C identifier")
                if app_name in seen_app_names:
                    errors.append(
                        f"{origin}: app_name '{app_name}' already used by "
                        f"{seen_app_names[app_name]}"
                    )
                seen_app_names[app_name] = origin

            limits = sig_cfg.get("limits")
            if limits:
                if not app_name:
                    errors.append(f"{origin}: limits requires an app_name")

                unknown = set(limits) - set(LIMIT_KEYS)
                if unknown:
                    errors.append(
                        f"{origin}: unknown limits keys {sorted(unknown)} "
                        f"(allowed: {list(LIMIT_KEYS)})"
                    )
                    continue

                non_numeric = [k for k in limits if not isinstance(limits[k], (int, float))]
                if non_numeric:
                    errors.append(f"{origin}: limits {non_numeric} are not numeric")
                    continue

                present_values = [limits[k] for k in LIMIT_KEYS if k in limits]
                if present_values != sorted(present_values):
                    errors.append(
                        f"{origin}: limits are not monotonic — expected "
                        f"critical_low <= warning_low <= warning_high <= critical_high"
                    )

    return errors


# ── DBC Filtering + cantools ──────────────────────────────────────────────────


def write_filtered_dbc(db: Database, selected: set[str], out_path: Path) -> None:
    """Dump a DBC containing only the messages selected in the YAML."""
    filtered = Database(
        messages=[m for m in db.messages if m.name in selected],
        nodes=db.nodes,
        buses=db.buses,
        version=db.version,
    )
    cantools.database.dump_file(filtered, str(out_path))


def run_cantools_codegen(dbc_path: Path, out_dir: Path) -> None:
    """Run `cantools generate_c_source` → dcu_can_gen.[ch] in out_dir."""
    cmd = [
        sys.executable, "-m", "cantools", "generate_c_source",
        "--database-name", "dcu_can_gen",
        "--use-float",
        "-o", str(out_dir),
        str(dbc_path),
    ]
    subprocess.run(cmd, check=True)


# ── Snapshot Struct + RX Dispatch Generation ─────────────────────────────────


def snapshot_c_type(sig) -> str:
    """Map a cantools signal to the C type used in the snapshot struct."""
    if sig.length == 1:
        return "bool"
    if sig.is_float or sig.scale != 1 or sig.offset != 0:
        return "float"
    base = "int" if sig.is_signed else "uint"
    for width in (8, 16, 32, 64):
        if sig.length <= width:
            return f"{base}{width}_t"
    raise ValueError(f"Signal {sig.name}: length {sig.length} not supported")


def collect_rx_messages(db: Database, cfg: dict) -> list[dict]:
    """
    Collect all direction==rx messages with their app_name-mapped signals.

    Returns a list of dicts:
      { "msg": cantools message, "snake": c_name,
        "signals": [(dbc_signal, app_name, c_type), ...] }
    Only signals with an app_name are included (selection at signal level).
    """
    dbc_messages = {m.name: m for m in db.messages}
    result = []

    for msg_name, msg_cfg in cfg["messages"].items():
        msg_cfg = msg_cfg or {}
        if msg_cfg.get("direction") != "rx":
            continue

        dbc_msg = dbc_messages[msg_name]
        dbc_signals = {s.name: s for s in dbc_msg.signals}
        mapped = []
        for sig_name, sig_cfg in (msg_cfg.get("signals") or {}).items():
            sig_cfg = sig_cfg or {}
            app_name = sig_cfg.get("app_name")
            if app_name:
                sig = dbc_signals[sig_name]
                mapped.append((sig, app_name, snapshot_c_type(sig), sig_cfg.get("limits")))

        if mapped:
            result.append({
                "msg": dbc_msg,
                "snake": camel_to_snake_case(msg_name),
                "signals": mapped,
            })

    return result


def emit_data_header(rx_messages: list[dict]) -> str:
    lines = [GENERATED_BANNER]
    lines.append("#pragma once\n")
    lines.append("#include <stdint.h>")
    lines.append("#include <stdbool.h>\n")
    lines.append("""\
/**
 * @brief Snapshot of all decoded RX CAN signal values.
 *
 * Fields correspond to the app_names from dcu_app.yaml. Populated by
 * can_rx_gen_dispatch(); published to the app layer via can_data_chan
 * and stored there in app_state.
 */
struct can_data_snapshot {""")
    for entry in rx_messages:
        msg = entry["msg"]
        lines.append(f"\n    /* ── {msg.name} (0x{msg.frame_id:03X}) ── */\n")
        for sig, app_name, c_type, _limits in entry["signals"]:
            lines.append(f"    {c_type:<8} {app_name};{'':<4}/**< {sig.name} */")
    lines.append("""
    /**
     * Zephyr uptime (ms) at the time of decoding.
     * Allows the app layer to detect stale data during CAN silence.
     */
    int64_t  timestamp_ms;
};""")
    return "\n".join(lines) + "\n"


def emit_rx_dispatch_header(rx_messages: list[dict]) -> str:
    lines = [GENERATED_BANNER]
    lines.append("#pragma once\n")
    lines.append("#include <stdint.h>")
    lines.append("#include <stdbool.h>\n")
    lines.append('#include "can_data_gen.h"\n')
    lines.append(f"""\
/** @brief Number of RX frame IDs (size of can_rx_gen_frame_ids). */
#define CAN_RX_GEN_NUM_FRAMES {len(rx_messages)}U

/**
 * @brief All RX frame IDs from dcu_app.yaml (direction: rx).
 * For filter setup: one can_add_rx_filter_msgq() call per entry.
 */
extern const uint32_t can_rx_gen_frame_ids[CAN_RX_GEN_NUM_FRAMES];

/**
 * @brief Decodes an RX frame and writes the signal values into @p snap.
 *
 * Handles all direction:rx messages from dcu_app.yaml. Fields without
 * a matching frame ID remain unchanged (accumulator semantics).
 *
 * @param frame_id  CAN frame ID (11-bit standard ID).
 * @param data      Frame payload buffer.
 * @param dlc       Number of valid payload bytes.
 * @param snap      Target snapshot; only fields of the matched message change.
 * @return          true if the frame ID was known and successfully decoded.
 */
bool can_rx_gen_dispatch(uint32_t frame_id, const uint8_t *data, uint8_t dlc,
                         struct can_data_snapshot *snap);""")
    return "\n".join(lines) + "\n"


def emit_rx_dispatch_source(rx_messages: list[dict]) -> str:
    lines = [GENERATED_BANNER]
    lines.append('#include "can_rx_gen.h"')
    lines.append(f'#include "{DATABASE_NAME}.h"\n')

    for entry in rx_messages:
        msg, snake = entry["msg"], entry["snake"]
        fn = f"{DATABASE_NAME}_{snake}"
        lines.append(f"/* ── {msg.name} (0x{msg.frame_id:03X}) ── */\n")
        lines.append(f"static bool apply_{snake}(const uint8_t *data, uint8_t dlc,")
        lines.append(f"{'':<{len('static bool apply_' + snake) + 1}}struct can_data_snapshot *snap)")
        lines.append("{")
        lines.append(f"    struct {fn}_t msg;\n")
        lines.append(f"    if ({fn}_unpack(&msg, data, dlc) != 0) {{")
        lines.append("        return false;")
        lines.append("    }\n")
        for sig, app_name, c_type, _limits in entry["signals"]:
            field = camel_to_snake_case(sig.name)
            if c_type == "bool":
                rhs = f"(msg.{field} != 0u)"
            elif c_type == "float":
                rhs = f"{fn}_{field}_decode(msg.{field})"
            else:
                rhs = f"msg.{field}"
            lines.append(f"    snap->{app_name:<24} = {rhs};")
        lines.append("\n    return true;")
        lines.append("}\n")

    ids = ",\n".join(
        f"    {DATABASE_NAME.upper()}_{e['snake'].upper()}_FRAME_ID"
        for e in rx_messages
    )
    lines.append(f"const uint32_t can_rx_gen_frame_ids[CAN_RX_GEN_NUM_FRAMES] = {{\n{ids},\n}};\n")

    lines.append("""\
bool can_rx_gen_dispatch(uint32_t frame_id, const uint8_t *data, uint8_t dlc,
                         struct can_data_snapshot *snap)
{
    switch (frame_id) {""")
    for entry in rx_messages:
        snake = entry["snake"]
        lines.append(f"    case {DATABASE_NAME.upper()}_{snake.upper()}_FRAME_ID:")
        lines.append(f"        return apply_{snake}(data, dlc, snap);")
    lines.append("""\
    default:
        return false;
    }
}""")
    return "\n".join(lines) + "\n"


# ── LVGL Subject Generation ───────────────────────────────────────────────────


def subject_kind(c_type: str) -> str:
    """Map a snapshot C type to the LVGL subject kind ('int' or 'float')."""
    return "float" if c_type == "float" else "int"


def c_float(value: float | int) -> str:
    return f"{float(value)}f"


def emit_subjects_header(rx_messages: list[dict]) -> str:
    lines = [GENERATED_BANNER]
    lines.append("#pragma once\n")
    lines.append("#include <lvgl.h>\n")
    lines.append('#include "can_data_gen.h"\n')
    lines.append("""\
/*
 * One value subject ui_subj_<x> per RX signal (app_name from dcu_app.yaml).
 * For signals with limits a level-binding helper ui_bind_level_<x>(lv_obj_t*)
 * wires LV_STATE_USER_1 (warning) and LV_STATE_USER_2 (critical) directly
 * against the value subject using lv_obj_bind_state_if_lt/gt.
 * LV_STATE_USER_2 has higher priority and overrides USER_1 when both fire.
 *
 * Threading: ui_subjects_gen_init() and ui_subjects_gen_update() must ONLY
 * be called from the LVGL thread — observers fire synchronously inside
 * lv_subject_set_*().
 *
 * Widget binding in screens:
 *   lv_label_bind_text(label, &ui_subj_voltage_tractive_system, "%d V");
 *   ui_bind_level_voltage_accu_hv(label);   // adds styles + state observers
 */
""")
    for entry in rx_messages:
        msg = entry["msg"]
        lines.append(f"/* ── {msg.name} (0x{msg.frame_id:03X}) ── */\n")
        for sig, app_name, c_type, limits in entry["signals"]:
            lines.append(f"extern lv_subject_t ui_subj_{app_name};{'':<4}"
                         f"/**< {sig.name} ({subject_kind(c_type)}) */")
            if limits:
                lines.append(
                    f"void ui_bind_level_{app_name}(lv_obj_t *obj);"
                    f"  /**< LV_STATE_USER_1=warn, USER_2=crit via {sig.name} */")
        lines.append("")
    lines.append("""\
/**
 * @brief Initializes all subjects to 0.
 * Call before screen creation so screens can bind widgets during construction.
 */
void ui_subjects_gen_init(void);

/**
 * @brief Transfers a CAN snapshot into all subjects.
 *
 * lv_subject_set_*() only notifies observers on value change.
 *
 * @param snap  Snapshot from UI_CMD_UPDATE_DATA (app layer → UI).
 */
void ui_subjects_gen_update(const struct can_data_snapshot *snap);""")
    return "\n".join(lines) + "\n"


def emit_subjects_source(rx_messages: list[dict]) -> str:
    all_signals = [
        (sig, app_name, c_type, limits)
        for entry in rx_messages
        for sig, app_name, c_type, limits in entry["signals"]
    ]

    lines = [GENERATED_BANNER]
    lines.append('#include "ui_subjects_gen.h"')
    lines.append('#include "modules/ui/ui_styles.h"\n')

    for _sig, app_name, _c_type, _limits in all_signals:
        lines.append(f"lv_subject_t ui_subj_{app_name};")

    lines.append("\nvoid ui_subjects_gen_init(void)\n{")
    for _sig, app_name, c_type, _limits in all_signals:
        if subject_kind(c_type) == "float":
            lines.append(f"    lv_subject_init_float(&ui_subj_{app_name}, 0.0f);")
        else:
            lines.append(f"    lv_subject_init_int(&ui_subj_{app_name}, 0);")
    lines.append("}\n")

    lines.append("void ui_subjects_gen_update(const struct can_data_snapshot *snap)\n{")
    for _sig, app_name, c_type, _limits in all_signals:
        if subject_kind(c_type) == "float":
            lines.append(f"    lv_subject_set_float(&ui_subj_{app_name}, snap->{app_name});")
        else:
            lines.append(f"    lv_subject_set_int(&ui_subj_{app_name}, (int32_t)snap->{app_name});")
    lines.append("}\n")

    for _sig, app_name, _c_type, limits in all_signals:
        if not limits:
            continue
        lines.append(f"void ui_bind_level_{app_name}(lv_obj_t *obj)")
        lines.append("{")
        lines.append( "    lv_obj_add_style(obj, &ui_style_level_warn, LV_STATE_USER_1);")
        lines.append( "    lv_obj_add_style(obj, &ui_style_level_crit, LV_STATE_USER_2);")
        if "warning_high" in limits:
            lines.append(f"    lv_obj_bind_state_if_gt(obj, &ui_subj_{app_name}, "
                         f"LV_STATE_USER_1, {c_float(limits['warning_high'])});")
        if "warning_low" in limits:
            lines.append(f"    lv_obj_bind_state_if_lt(obj, &ui_subj_{app_name}, "
                         f"LV_STATE_USER_1, {c_float(limits['warning_low'])});")
        if "critical_high" in limits:
            lines.append(f"    lv_obj_bind_state_if_gt(obj, &ui_subj_{app_name}, "
                         f"LV_STATE_USER_2, {c_float(limits['critical_high'])});")
        if "critical_low" in limits:
            lines.append(f"    lv_obj_bind_state_if_lt(obj, &ui_subj_{app_name}, "
                         f"LV_STATE_USER_2, {c_float(limits['critical_low'])});")
        lines.append("}\n")

    return "\n".join(lines) + "\n"


# ── Main ──────────────────────────────────────────────────────────────────────


def main() -> None:
    args = parse_args()

    if not args.dbc.is_file():
        fail([f"DBC not found: {args.dbc}"])
    if not args.yaml_path.is_file():
        fail([f"YAML not found: {args.yaml_path}"])

    db = cantools.database.load_file(str(args.dbc))
    with open(args.yaml_path, encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    errors = validate(db, cfg)
    if errors:
        fail(errors)

    selected = set(cfg["messages"].keys())
    args.out.mkdir(parents=True, exist_ok=True)

    # Stage 1: filtered DBC → cantools C code
    with tempfile.TemporaryDirectory() as tmp:
        filtered_dbc = Path(tmp) / "dcu_can_filtered.dbc"
        write_filtered_dbc(db, selected, filtered_dbc)
        run_cantools_codegen(filtered_dbc, args.out)

    # Stage 2: snapshot struct + RX dispatch
    rx_messages = collect_rx_messages(db, cfg)
    (args.out / "can_data_gen.h").write_text(emit_data_header(rx_messages), encoding="utf-8")
    (args.out / "can_rx_gen.h").write_text(emit_rx_dispatch_header(rx_messages), encoding="utf-8")
    (args.out / "can_rx_gen.c").write_text(emit_rx_dispatch_source(rx_messages), encoding="utf-8")

    # Stage 3: LVGL subjects + level-binding helpers
    (args.out / "ui_subjects_gen.h").write_text(
        emit_subjects_header(rx_messages), encoding="utf-8")
    (args.out / "ui_subjects_gen.c").write_text(
        emit_subjects_source(rx_messages), encoding="utf-8")

    total_signals = sum(
        len((m or {}).get("signals") or {}) for m in cfg["messages"].values()
    )
    rx_signal_count = sum(len(e["signals"]) for e in rx_messages)
    limited_count = sum(
        1 for e in rx_messages
        for _sig, _app_name, _c_type, limits in e["signals"]
        if limits
    )
    print(f"OK: {len(selected)} messages ({len(db.messages)} in DBC), "
          f"{total_signals} signals mapped, {limited_count} with level bindings")
    print(f"    RX dispatch: {len(rx_messages)} messages, "
          f"{rx_signal_count} snapshot fields")
    for name in ("dcu_can_gen.c", "dcu_can_gen.h", "can_data_gen.h",
                 "can_rx_gen.c", "can_rx_gen.h",
                 "ui_subjects_gen.c", "ui_subjects_gen.h"):
        print(f"  → {args.out / name}")


if __name__ == "__main__":
    main()